# Generated by Django 6.0.1 on 2026-01-29 12:49

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='stats',
            field=models.JSONField(default=store.models.default_stats),
        ),
    ]
