# Generated by Django 6.0.1 on 2026-01-29 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_artisan_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='artisan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.artisan'),
        ),
    ]
