# Generated by Django 6.0.1 on 2026-02-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='craft_story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
