# Generated by Django 6.0.1 on 2026-02-17 05:59

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(models.OrderBy(django.db.models.functions.text.Lower('title'), descending=True), name='lower_title_date_idx'),
        ),
    ]
