# Generated by Django 6.0.2 on 2026-02-20 20:29

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_artisan_craft_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store/products/images', validators=[store.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='store/products/videos', validators=[store.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='productasset',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='store/assets/videos', validators=[store.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='productasset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store/assets/images', validators=[store.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='productasset',
            name='mesh',
            field=models.FileField(blank=True, null=True, upload_to='store/assets/models', validators=[store.validators.validate_model_extension]),
        ),
    ]
