# Generated by Django 6.0.1 on 2026-02-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_lower_title_date_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='lower_title_idx',
            old_name='lower_title_date_idx',
        ),
    ]
