# Generated by Django 6.0.1 on 2026-02-17 06:26

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_lower_title_date_idx_lower_title_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='lower_title_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(django.db.models.functions.text.Lower('title'), name='title_idx'),
        ),
    ]
