# Generated by Django 6.0.2 on 2026-02-20 22:00

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='artisan/profiles', validators=[store.validators.validate_file_size]),
        ),
    ]
