# Generated by Django 6.0.2 on 2026-02-21 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_lower_title_idx_product_title_idx'),
        ('store', '0009_artisan_profile_image'),
    ]

    operations = [
    ]
