# Generated by Django 6.0.2 on 2026-05-23 13:18

import django.db.models.deletion
import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_merge_20260221_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pechan_card_file', models.ImageField(help_text='Pechan Card or State Handicraft Board Certificate', upload_to='verification/pechan_cards', validators=[store.validators.validate_file_size])),
                ('pechan_card_number', models.CharField(max_length=100)),
                ('generational_lineage', models.CharField(choices=[('first', '1st Generation'), ('second', '2nd Generation'), ('third_plus', '3rd Generation+'), ('community', 'Community/SHG Trained')], max_length=20)),
                ('artisan_bio', models.TextField(help_text='Heritage story and craft learning journey')),
                ('has_gi_tag', models.BooleanField(default=False)),
                ('gi_tag_number', models.CharField(blank=True, help_text='GI Tag registration number if applicable', max_length=50, null=True)),
                ('raw_material_source', models.TextField(help_text='Description of traditional raw material sources')),
                ('tooling_method', models.CharField(choices=[('handcrafted', '100% Handcrafted'), ('handloom', 'Handloom Operated'), ('hand_tooled', 'Hand-tooled with Assistive Machinery')], max_length=20)),
                ('process_video_file', models.FileField(help_text='30-60 second video showing crafting process', upload_to='verification/process_videos', validators=[store.validators.validate_file_size])),
                ('workshop_photo_file', models.ImageField(help_text='Photo of workshop/studio space', upload_to='verification/workshop_photos', validators=[store.validators.validate_file_size])),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('NEEDS_INFO', 'Needs Additional Information')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True, null=True)),
                ('artisan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='store.artisan')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
